-- AlterTable
ALTER TABLE "Profile" ALTER COLUMN "phoneNumber" DROP NOT NULL,
ALTER COLUMN "bio" SET DEFAULT NULL,
ALTER COLUMN "preferredLocation" SET DEFAULT NULL,
ALTER COLUMN "cvLink" SET DEFAULT NULL,
ALTER COLUMN "professionalSummary" SET DEFAULT NULL;
