-- AlterTable
ALTER TABLE "Profile" ALTER COLUMN "bio" SET DEFAULT NULL,
ALTER COLUMN "isOpenToWork" DROP NOT NULL,
ALTER COLUMN "isOpenToRelocation" DROP NOT NULL,
ALTER COLUMN "preferredLocation" SET DEFAULT NULL,
ALTER COLUMN "cvLink" SET DEFAULT NULL,
ALTER COLUMN "professionalSummary" SET DEFAULT NULL;
